version: '3'

services:
  web:
    build: web
    #image: registry.jorith.nl/blikjesteller/web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blikjesteller.rule=Host(`blikje.jorith.nl`)"
      - "traefik.http.routers.blikjesteller.entrypoints=websecure"
      - "traefik.http.routers.blikjesteller.middlewares=default@file"
      - "com.centurylinklabs.watchtower.enable=false"
networks:   
  default:
    external:
      name: proxy
