node {
    checkout scm

    def app

    stage('Build') {
        sh 'mvn clean package'
    }

    stage ('Deploy') {

        sh "docker-compose up -d"

        emailext body: 'Deployed new version to production.', subject: 'Blikjesteller API', to: 'jorith@gmail.com'
    }
}